package minerva.view.panel;

import minerva.controller.ControllerPanelProducto;
import minerva.controller.ControllerSystem;

/**
 *
 * @author L
 */
public class PanelProducto extends javax.swing.JPanel {

    // CONTROLLER
    ControllerPanelProducto productoController = null;
    
    public PanelProducto(ControllerSystem systemController) {
        productoController = new ControllerPanelProducto(systemController);
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        REGISTRO = new javax.swing.JTabbedPane();
        panel_4 = new javax.swing.JPanel();
        codigo_panel_4 = new javax.swing.JLabel();
        nombreTextFiel = new javax.swing.JTextField();
        descripcion_panel_4 = new javax.swing.JLabel();
        precioTextField = new javax.swing.JTextField();
        cantidad_panel_4 = new javax.swing.JLabel();
        stockTextField = new javax.swing.JTextField();
        precio_panel_4 = new javax.swing.JLabel();
        CodigoBarrasTextField = new javax.swing.JTextField();
        proveedor_4 = new javax.swing.JLabel();
        tabla_productos = new javax.swing.JScrollPane();
        TablaRegistro = new javax.swing.JTable();
        botonGuardar_4 = new javax.swing.JButton();
        botonEliminar_4 = new javax.swing.JButton();
        descripcionnTextField = new javax.swing.JTextField();
        CONSULTA = new javax.swing.JPanel();
        tabla_productos1 = new javax.swing.JScrollPane();
        tablaConsulta = new javax.swing.JTable();
        botonNuevo_5 = new javax.swing.JButton();
        precioTXT_5 = new javax.swing.JTextField();
        precio_panel_5 = new javax.swing.JLabel();
        botonActualizar = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        REGISTRO.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                REGISTROComponentAdded(evt);
            }
        });

        panel_4.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                panel_4ComponentAdded(evt);
            }
        });

        codigo_panel_4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        codigo_panel_4.setText("NOMBRE");

        nombreTextFiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextFielActionPerformed(evt);
            }
        });

        descripcion_panel_4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        descripcion_panel_4.setText("PRECIO");

        cantidad_panel_4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        cantidad_panel_4.setText("STOCK");

        stockTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockTextFieldActionPerformed(evt);
            }
        });

        precio_panel_4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        precio_panel_4.setText("CODIGO BARRAS");

        proveedor_4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        proveedor_4.setText("DESCRIPCION");

        TablaRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "PRECIO", "DESCRIPCION", "STOCK"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_productos.setViewportView(TablaRegistro);

        botonGuardar_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuardarTodo.png"))); // NOI18N
        botonGuardar_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        botonEliminar_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        botonEliminar_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panel_4Layout = new javax.swing.GroupLayout(panel_4);
        panel_4.setLayout(panel_4Layout);
        panel_4Layout.setHorizontalGroup(
            panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_4Layout.createSequentialGroup()
                .addGroup(panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(precioTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_4Layout.createSequentialGroup()
                                    .addComponent(proveedor_4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(descripcionnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panel_4Layout.createSequentialGroup()
                                    .addComponent(botonEliminar_4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonGuardar_4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(19, 19, 19))
                                .addGroup(panel_4Layout.createSequentialGroup()
                                    .addComponent(precio_panel_4)
                                    .addGap(18, 18, 18)
                                    .addComponent(CodigoBarrasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panel_4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_4Layout.createSequentialGroup()
                                .addComponent(cantidad_panel_4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(stockTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_4Layout.createSequentialGroup()
                                .addGroup(panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(descripcion_panel_4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel_4Layout.createSequentialGroup()
                                        .addComponent(codigo_panel_4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(nombreTextFiel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(tabla_productos, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_4Layout.setVerticalGroup(
            panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_4Layout.createSequentialGroup()
                        .addComponent(tabla_productos, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panel_4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreTextFiel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigo_panel_4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(precioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descripcion_panel_4))
                        .addGap(42, 42, 42)
                        .addGroup(panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stockTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidad_panel_4))
                        .addGap(44, 44, 44)
                        .addGroup(panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(proveedor_4)
                            .addComponent(descripcionnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CodigoBarrasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precio_panel_4))
                        .addGap(67, 67, 67)
                        .addGroup(panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonGuardar_4, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(botonEliminar_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31))))
        );

        REGISTRO.addTab("REGISTRO", panel_4);

        tablaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "PRECIO", "DESCRIPCION", "STOCK", "CODIGOBARRAS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_productos1.setViewportView(tablaConsulta);

        botonNuevo_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo.png"))); // NOI18N
        botonNuevo_5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        precioTXT_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioTXT_5ActionPerformed(evt);
            }
        });

        precio_panel_5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        precio_panel_5.setText("CODIGO BARRAS");

        botonActualizar.setText("ACTUALIZAR PRODUCTO");
        botonActualizar.setToolTipText("");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        jLabel1.setText("MODO");

        javax.swing.GroupLayout CONSULTALayout = new javax.swing.GroupLayout(CONSULTA);
        CONSULTA.setLayout(CONSULTALayout);
        CONSULTALayout.setHorizontalGroup(
            CONSULTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CONSULTALayout.createSequentialGroup()
                .addGroup(CONSULTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CONSULTALayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(precio_panel_5))
                    .addGroup(CONSULTALayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(botonNuevo_5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CONSULTALayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1))
                    .addGroup(CONSULTALayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(precioTXT_5, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CONSULTALayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(botonActualizar)))
                .addGap(12, 12, 12)
                .addComponent(tabla_productos1, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
                .addContainerGap())
        );
        CONSULTALayout.setVerticalGroup(
            CONSULTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CONSULTALayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(precio_panel_5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(precioTXT_5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(botonNuevo_5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CONSULTALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabla_productos1)
                .addContainerGap())
        );

        REGISTRO.addTab("CONSULTA", CONSULTA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(REGISTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(REGISTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void REGISTROComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_REGISTROComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_REGISTROComponentAdded

    private void panel_4ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_panel_4ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_4ComponentAdded

    private void nombreTextFielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextFielActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextFielActionPerformed

    private void precioTXT_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioTXT_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioTXT_5ActionPerformed

    private void stockTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockTextFieldActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CONSULTA;
    private javax.swing.JTextField CodigoBarrasTextField;
    private javax.swing.JTabbedPane REGISTRO;
    private javax.swing.JTable TablaRegistro;
    private javax.swing.JCheckBox botonActualizar;
    private javax.swing.JButton botonEliminar_4;
    private javax.swing.JButton botonGuardar_4;
    private javax.swing.JButton botonNuevo_5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel cantidad_panel_4;
    private javax.swing.JLabel codigo_panel_4;
    private javax.swing.JLabel descripcion_panel_4;
    private javax.swing.JTextField descripcionnTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nombreTextFiel;
    private javax.swing.JPanel panel_4;
    private javax.swing.JTextField precioTXT_5;
    private javax.swing.JTextField precioTextField;
    private javax.swing.JLabel precio_panel_4;
    private javax.swing.JLabel precio_panel_5;
    private javax.swing.JLabel proveedor_4;
    private javax.swing.JTextField stockTextField;
    private javax.swing.JTable tablaConsulta;
    private javax.swing.JScrollPane tabla_productos;
    private javax.swing.JScrollPane tabla_productos1;
    // End of variables declaration//GEN-END:variables
}
