package minerva.view.panel;

import javax.swing.table.DefaultTableModel;
import minerva.controller.ControllerNuevaVentaPanel;
import minerva.controller.ControllerSystem;

/**
 *
 * @author L
 */
public class PanelNuevaVenta extends javax.swing.JPanel {
    // CONTROLLER
    ControllerNuevaVentaPanel nuevaVentaController = null;
    
    // INSTANCIAS PARA INTERACTUAR CON LA TABLA
    DefaultTableModel model;
    
    public PanelNuevaVenta(ControllerSystem systemController) {
        initComponents();
        model = (DefaultTableModel) tablaNuevaVenta.getModel();
        nuevaVentaController= new ControllerNuevaVentaPanel(systemController);
        asignarDatosVendedorPanel();
        asignarDatosClientePanel();
    }
      
    private void asignarDatosVendedorPanel() {
        vendedorUsuarioTextField.setText(nuevaVentaController.getUsuarioVendendor());
    }
    
    private void asignarDatosClientePanel() {
        nombreClienteTextField.setText(nuevaVentaController.getNombreCliente());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TablaPanel = new javax.swing.JTabbedPane();
        panel_1 = new javax.swing.JPanel();
        VendedorLabel = new javax.swing.JLabel();
        ClienteLabel = new javax.swing.JLabel();
        nombreClienteTextField = new javax.swing.JTextField();
        stockLabel = new javax.swing.JLabel();
        eliminar = new javax.swing.JButton();
        tabla_nuevaVenta = new javax.swing.JScrollPane();
        tablaNuevaVenta = new javax.swing.JTable();
        botonRegistrarEImprimir = new javax.swing.JButton();
        TotalAPagarLabel = new javax.swing.JLabel();
        TotalPagarTextField = new javax.swing.JLabel();
        botonImprimir = new javax.swing.JButton();
        botonFinalizarVenta = new javax.swing.JButton();
        codigoLabel = new javax.swing.JLabel();
        javax.swing.JTextField cantidadTextField = new javax.swing.JTextField();
        CantidadLabel = new javax.swing.JLabel();
        vendedorUsuarioTextField = new javax.swing.JLabel();
        stockTextField = new javax.swing.JLabel();
        botonRegistrarVentaTabla = new javax.swing.JButton();
        javax.swing.JTextField codigoBarrasTextField = new javax.swing.JTextField();

        TablaPanel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                TablaPanelAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        VendedorLabel.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        VendedorLabel.setText("Vendedor");

        ClienteLabel.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        ClienteLabel.setText("Cliente");

        nombreClienteTextField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        stockLabel.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        stockLabel.setText("Stock ");

        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        tablaNuevaVenta.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tablaNuevaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "COD", "PRODUCTO", "DESCRIPCION", "CANTIDAD", "PRECIO U.", "MONTO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_nuevaVenta.setViewportView(tablaNuevaVenta);
        if (tablaNuevaVenta.getColumnModel().getColumnCount() > 0) {
            tablaNuevaVenta.getColumnModel().getColumn(0).setPreferredWidth(5);
            tablaNuevaVenta.getColumnModel().getColumn(1).setPreferredWidth(50);
            tablaNuevaVenta.getColumnModel().getColumn(2).setPreferredWidth(100);
            tablaNuevaVenta.getColumnModel().getColumn(5).setPreferredWidth(15);
        }

        botonRegistrarEImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/print.png"))); // NOI18N
        botonRegistrarEImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrarEImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarEImprimirProductoActionPerformed(evt);
            }
        });

        TotalAPagarLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TotalAPagarLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/money.png"))); // NOI18N
        TotalAPagarLabel.setText("TOTAL A PAGAR");

        TotalPagarTextField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TotalPagarTextField.setText("-----");

        botonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/print.png"))); // NOI18N
        botonImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonImprimirActionPerformed(evt);
            }
        });

        botonFinalizarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/print.png"))); // NOI18N
        botonFinalizarVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonFinalizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinalizarVentaregistrarProductoActionPerformed(evt);
            }
        });

        codigoLabel.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        codigoLabel.setText("Codigo");

        cantidadTextField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cantidadTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadTextFieldActionPerformed(evt);
            }
        });
        cantidadTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadTextFieldKeyTyped(evt);
            }
        });

        CantidadLabel.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        CantidadLabel.setText("Cantidad");

        vendedorUsuarioTextField.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N

        stockTextField.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N

        botonRegistrarVentaTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/print.png"))); // NOI18N
        botonRegistrarVentaTabla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrarVentaTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarVentaTablaActionPerformed(evt);
            }
        });

        codigoBarrasTextField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        codigoBarrasTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoBarrasTextFieldActionPerformed(evt);
            }
        });
        codigoBarrasTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoBarrasTextFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panel_1Layout = new javax.swing.GroupLayout(panel_1);
        panel_1.setLayout(panel_1Layout);
        panel_1Layout.setHorizontalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VendedorLabel)
                    .addComponent(vendedorUsuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ClienteLabel)
                    .addComponent(nombreClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(eliminar)
                .addGap(19, 19, 19))
            .addGroup(panel_1Layout.createSequentialGroup()
                .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(codigoLabel)
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(codigoBarrasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CantidadLabel)
                    .addComponent(cantidadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(botonRegistrarVentaTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(botonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonRegistrarEImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonFinalizarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(TotalAPagarLabel)
                .addGap(42, 42, 42)
                .addComponent(TotalPagarTextField)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabla_nuevaVenta)
                .addContainerGap())
        );
        panel_1Layout.setVerticalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_1Layout.createSequentialGroup()
                .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VendedorLabel)
                            .addComponent(stockLabel)
                            .addComponent(ClienteLabel))
                        .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombreClienteTextField)
                                    .addComponent(vendedorUsuarioTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(stockTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))))
                    .addGroup(panel_1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(eliminar)))
                .addGap(21, 21, 21)
                .addComponent(tabla_nuevaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonRegistrarEImprimir)
                    .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TotalAPagarLabel)
                        .addComponent(TotalPagarTextField))
                    .addComponent(botonFinalizarVenta)
                    .addComponent(botonImprimir)
                    .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panel_1Layout.createSequentialGroup()
                            .addComponent(CantidadLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cantidadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(codigoBarrasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panel_1Layout.createSequentialGroup()
                            .addComponent(codigoLabel)
                            .addGap(28, 28, 28)))
                    .addComponent(botonRegistrarVentaTabla))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        TablaPanel.addTab("NuevaVenta", panel_1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(TablaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(TablaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TablaPanelAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TablaPanelAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaPanelAncestorMoved

    private void botonRegistrarVentaTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarVentaTablaActionPerformed
        long codigoBarras;
        try {
            //codigoBarras = Integer.parseInt(codigoBarrasTextField.getText());
        } catch (Exception e) {
            return;
        }
        //Object[] producto = nuevaVentaController.consultarDatosProducto(codigoBarras);
//        Object[] object = new Object[model.getColumnCount()];
//        
//        object[0] = producto[0];
//        object[1] = producto[1];
//        object[2] = producto[3];
//        object[3] = cantidadTextField.getText();
//        object[4] = producto[2];
//        object[5] = 5000;
        
        //model.addRow(object); 
    }//GEN-LAST:event_botonRegistrarVentaTablaActionPerformed

    private void cantidadTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadTextFieldActionPerformed

    private void botonFinalizarVentaregistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFinalizarVentaregistrarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonFinalizarVentaregistrarProductoActionPerformed

    private void botonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonImprimirActionPerformed

    private void botonRegistrarEImprimirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarEImprimirProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistrarEImprimirProductoActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarActionPerformed

    private void cantidadTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadTextFieldKeyTyped
        // CODIGO PARA QUE SOLAMENTE SE PUEDAN INGRESAR NUMEROS
        char c = evt.getKeyChar();
        
        if (c<'0' || c> '9') {
            evt.consume();            
        }
    }//GEN-LAST:event_cantidadTextFieldKeyTyped

    private void codigoBarrasTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoBarrasTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoBarrasTextFieldActionPerformed

    private void codigoBarrasTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoBarrasTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoBarrasTextFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CantidadLabel;
    private javax.swing.JLabel ClienteLabel;
    private javax.swing.JTabbedPane TablaPanel;
    private javax.swing.JLabel TotalAPagarLabel;
    private javax.swing.JLabel TotalPagarTextField;
    private javax.swing.JLabel VendedorLabel;
    private javax.swing.JButton botonFinalizarVenta;
    private javax.swing.JButton botonImprimir;
    private javax.swing.JButton botonRegistrarEImprimir;
    private javax.swing.JButton botonRegistrarVentaTabla;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField nombreClienteTextField;
    private javax.swing.JPanel panel_1;
    private javax.swing.JLabel stockLabel;
    private javax.swing.JLabel stockTextField;
    private javax.swing.JTable tablaNuevaVenta;
    private javax.swing.JScrollPane tabla_nuevaVenta;
    private javax.swing.JLabel vendedorUsuarioTextField;
    // End of variables declaration//GEN-END:variables
}
